### PR TITLE
LPS-149738 - Include border color utility classes in Dialect

### PR DESCRIPTION
**Pull request by ethib137**

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
Thanks @ilzamcmed! Take a look at the additional changes I made and let me know if you have any questions.

**Comment by ilzamcmed** [comment]
Great changes! And how did I not think of this before?  Thank you @ethib137!

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
