### PR TITLE
HR_249 LPS-165427 Add site name to title

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-165427

The site name was missing for the title in the banner and so the SR was only announcing "Go to" which may cause confusion. 
With this fix the SR will not announce "Go to Liferay" which is the site name.

Let me know if there are any questions or comments with this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Looks good! Thanks @fortunatomaldonado

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
