### PR TITLE
HR_146 & HR_271 | LPS-165248 remove unnecessary markup for fieldset

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
Hello @ethib137,

This fix resolves the issues for HR_146 & HR_271 where the screen reader reads out the `href `link for `fieldsets`. 
I was able to resolve this by removing the `legend `and `aria-hidden` for the fieldsets. This allows the screen reader to read out the name of the `fieldset `and whether or not the button is expanded or collapsed.

Please let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Thanks @fortunatomaldonado. I added some updates in this pr: https://github.com/ethib137/liferay-portal/pull/69. Please take a look at my changes and let me know if you have any questions.

**Pull request closed without merging**
