### PR TITLE
LPS-149717 - Include background and text color variations

### PR DESCRIPTION
**Pull request by ilzamcmed**

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:sf:test

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:forward

**Comment by ethib137** [comment]
Thanks @ilzamcmed this looks good!

ci:forward

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
