### PR TITLE
LPS-165106

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-165106](https://issues.liferay.com/browse/LPS-165106) HR_172 Added role=button to Page template other options.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
resent here https://github.com/liferay-echo/liferay-portal/pull/9875

**Pull request closed without merging**
