### PR TITLE
LPS-164958 / HR_112 - search results are not being announced

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-164958

Hi Evan!

Here's a pull with two parts. 

The first is to cover the second point in HR_112's description where screen readers aren't announcing the search results. The reasoning behind the changes is due to the fact that the search results are essentially rendered as a new page (rather than being added on an existing one), we unfortunately can't use role="status" or aria-live="polite" since the screen reader simply won't recognize it as a 'changed' area. Therefore the only viable alternative is to announce it as an alert (see: https://github.com/w3c/aria/issues/1360). As a note, I misread your analysis previously so I made these changes, but feel free to leave them out if you think they're unnecessary or change too much. 

The second part is to cover the third note you made and makes the clear link more descriptive.

Let me know if there's anything you need me to clarify. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Thanks @wanderlast, yeah we will leave out the extra role="alert" for now. If the customer isn't satisfied with our redirect explanation we may add it back in.

Updating the aria-label for the clear button looks good, but we need two new language keys created `clear-x-result-for-x` and `clear-x-results-for-x`. This is because concatenating language keys may work for english but it won't always work correctly in other languages that have a different grammatical order. 

Can you update the pull with these changes? Thanks.

**Comment by wanderlast** [comment]
Hi @ethib137,

Got it! I've taken out the alert commit and added new language keys as requested.

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
