### PR TITLE
LPS-165248 - Screen Reader announcing extra information for fieldset elements

### PR DESCRIPTION
**Pull request by ethib137**
For the toggle button of our collapse panels, the screen reader is announcing the href instead of a human understandable label. This is because the label within had the `aria-hidden="true"` attribute added as a part of [this ticket](https://issues.liferay.com/browse/LPS-134141). 

The `aria-hidden` attribute was added to "avoid redundancy"
> Since the label of collapsible fieldsets are shown inside an <a> element, it's necessary for the <legend> to include an sr-only label and for the header to include aria-hidden="true" to avoid redundancy.

This is not actually avoiding redundancy though, because the <legend> and the label inside the anchor have different purposes and are announced differently by screen readers. The legend indicates the start and purpose of a group of fields inside a fieldset. The label inside the anchor is announced as a toggle button to open and close the entire fieldset.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1267401_5412

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1277401_5335

**Comment by ethib137** [comment]
ci:reevaluate:1277401_5335

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:reevaluate:1297401_5010

**Comment by ethib137** [comment]
ci:forward

**Comment by ethib137** [comment]
Forced Forward: https://github.com/brianchandotcom/liferay-portal/pull/124581

**Pull request closed without merging**
