### PR TITLE
LPS-152248 Fix tokens names

### PR DESCRIPTION
**Pull request by eduardobbgf**

### CODE REVIEW

**Comment by eduardobbgf** [comment]
ci:test:sf

**Comment by eduardobbgf** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1377401_1875

**Comment by ethib137** [comment]
Hey @eduardobbgf this looks good... can you rebase, re-push, and re-test. Hopefully that will get the checks to pass.

**Comment by eduardobbgf** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
