### PR TITLE
LPS-165395 | [HR_168] Changed h6 tag to h3 to maintain headings hierarchy

### PR DESCRIPTION
**Pull request by rebsilva**
**Related Issue:** https://issues.liferay.com/browse/LPS-165395

**Related HRs:**

- HR_168 (fixes partially, needs [this fix](https://github.com/ethib137/liferay-portal/pull/67) to be merged ) :warning:

**The solution:** Change the `<h6>` into a `<h3>` tag to follow the hierarchy.

**Reproduction Steps:**

1. Turn on JAWS and navigate to Site Builder > Pages.
2. Click on the + button to add a new page
3. Observe the Basic Templates page and Press H using JAWS to navigate between the headings.

**Expected Results**
Screen reader announces only one `<h1>` that is the title of the respective page ("Select Template"), along with two `<h2>` sr-only tags "admin-header" and "navigation". Also the other headers follow the right hierarchy, going from `<h2>` to `<h3>` etc.

:warning: **ATTENTION: The expected result will only fully happen when the https://github.com/ethib137/liferay-portal/pull/67 is merged.**

**Actual Results**
Screen reader announce two `<h1>` sr-only tags "admin-header" and "navigation" and the header hierarchy is not being followed, having a `<h6>` after a `<h2>`.

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by ethib137** [comment]
Hi @rebsilva can you update the ticket with steps to reproduce as described [here](https://github.com/ethib137/liferay-portal/pull/67#issuecomment-1276234687).

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
This [com.liferay.layout.seo.web.internal.util.TitleProviderTest.testGetTitle](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/117777//testReport/com.liferay.layout.seo.web.internal.util/TitleProviderTest/testGetTitle) test seems to be failing constatly, I will take a look if it is related.

**Comment by ethib137** [comment]
ci:reevaluate:1257401_4968

**Comment by catarineaguiar** [comment]
@rebsilva @ethib137 failures not related. Pull looks good to go.

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/9934

The design was a bit off with the change @ethib137 I have updated that :)

**Comment by victorg1991** [comment]
ci:close

**Pull request closed without merging**
