### PR TITLE
LPS-165667 | [HR_93] Giving buttons a proper meaning to SR

### PR DESCRIPTION
**Pull request by EugenioAntunes**
**Related Issue :** [LPS-165667](https://issues.liferay.com/browse/LPS-165667)

**Related HR:**

- HR_93

**The solution:** I added the correct `aria-label` to each button at 

**Test Description Step to Reproduce:**
1. Open the url: https://hrportaldev.bankofamerica.com/
 2. Expand the left navigation panel
 3. Navigate to Content and Data > Web Content > Structures
 4. Navigate to New button
 5. Press enter on new button

**Issue Description Actual Result:**
1. SR is announcing the search Icon is as unlabeled 1 button. This present across the application (Reproduced)
 2. SR is announcing the Fields and Fieldsets both are selected when Fields tab is selected (Not Reproduced)
 -While I was testing the SR has annouced properly both "field" as well as "fieldset". It was tested using Google Chrome version 106.0.5249.103 and JAWS version 2022.2207.25 ILM.
 4. SR is announcing the three dotted button under Fieldsets tab is as unlabeled zero button (Reproduced)

**Expected Result:**
SR should announce the correct label and SR should announce the correct state for the tabs

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Resent here: https://github.com/liferay-echo/liferay-portal/pull/9930

**Comment by victorg1991** [comment]
ci:close

**Pull request closed without merging**
