### PR TITLE
LPS-165400 | [HR_155] Title to buttons

### PR DESCRIPTION
**Pull request by igor-franca**
Related Issue: https://issues.liferay.com/browse/LPS-165400

Related HR: HR_155 
Add title to two buttons: Search and Back button

Reproduction Steps:

1. Turn on JAWS and navigate to Documents & Media.
2. Navigate "Menu button to the top left. Click on Content and Data-> Documents & Media->Document types ->Add new Document types.
3. Navigate the toggle buttons beside the side navigation bar.
4. Click on "Builder" button. Focus on "search icon" in the side bar.

Expected Results
HR_155:   1.Search button in side bar 2.Back button for all the elements in the fields section

Actual Results
HR:_155: Significant image buttons do not have proper alt text Example: Search button

### CODE REVIEW

**Comment by ethib137** [comment]
Hey @marcoscv-work, would it make sense to use the `title` attribute for icon buttons like this instead of `aria-label` so that the extra information on what the button does is available to sighted users on hover as well?

**Comment by marcoscv-work** [comment]
> Hey @marcoscv-work, would it make sense to use the `title` attribute for icon buttons like this instead of `aria-label` so that the extra information on what the button does is available to sighted users on hover as well?

Use titles or not is usually a design decision, if the icon is not clear enough we should use tooltip/titles so yes, probably a tooltip/title fits better:

https://liferay.design/lexicon/core-components/popovers-tooltips/#tooltips
https://clayui.com/docs/components/tooltip.html

**Comment by ethib137** [comment]
Thanks @marcoscv-work. @M-IgorFranca can you update this pr with that approach?

**Comment by M-IgorFranca** [comment]
Of course! thanks for review, I will make this change.

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Thanks @M-IgorFranca. Looks good!

**Comment by ethib137** [comment]
ci:forward

**Comment by ethib137** [comment]
Hey @M-IgorFranca thanks for the updates. In order for this to render as a tooltip in Liferay and not just as the native html title, we need to include the class `lfr-portal-tooltip` on the element has the title attribute. Can you make sure that is working properly and add screenshots to the ticket of it working correctly in each of the button locations? Thanks.

**Comment by M-IgorFranca** [comment]
Hi, ethib137, thanks for advised! I checked before committing, and the title insert one tool-tip. Sorry for not attached the screen shots, I too checked if the screen reader was reading correct.

image

image

Let me know if i can still add lfr-portal-tooltip for something i couldn't figure out. Thanks!

**Comment by M-IgorFranca** [comment]
> Hi, @ethib137, thanks for advised! I checked before committing, and the title insert one tool-tip. Sorry for not attached the screen shots, I too checked if the screen reader was reading correct.
> 
> image
> 
> image
> 
> Let me know if i can still add lfr-portal-tooltip for something i couldn't figure out. Thanks!

resent [here](https://github.com/liferay-lima/liferay-portal/pull/3616)

**Pull request closed without merging**
