### PR TITLE
HR_95 Prevent focus traps in codemirror editor

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-164875

Hello @ethib137,

I was able to find this issue and fix it in Page Templates, Templates, and Fragments.

For this issue, I decided to use `Ctrl M` in order to disable the `tab` functionality in the editor and make it possible to change focus. 
I decided to use this instead of `Esc` since in HTML Editor Modal in Page layout will close if pressed Esc. I also found that these keys are recognized as a way to change the `tab` behavior in editors. 
https://stackoverflow.com/questions/30112415/what-is-accessibility-mode-for-ctrl-m

I was not able to get the screen reader to announce the new commands using `aria-describedby` so I decided to use `aria-label`s instead. Let me know if this should be changed and how to go about implementing it.

Let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Hey @fortunatomaldonado thanks for your work on this. These are helpful points. 

I discovered that the reason why Jaws isn't reading the described-by is because there is a [bug with Jaws](https://github.com/FreedomScientific/VFO-standards-support/issues/643). It's still the right way to add this kind of message though, so we should still take that approach since a label "[should be concise](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby)". We should actually be adding a Label and a description for these.

Label can be passed into the constructor:
```
screenReaderLabel: MODES[mode].name,
```
And aria-description can be added to the focused element using this:
```
codeMirror.display.input.getField().setAttribute('aria-describedby', `${MODES[mode].name}SRDescription`);
```
Then we can add the element with the description above the wrapper. It won't be read by Jaws, but it's the right way to do it.

We also need to make sure that anything that will be ready by the screen reader is translated, so we need to include language keys as well.

This was definitely more complicated than it initially appeared. Let me know if you have any additional questions. Thanks.

**Comment by fortunatomaldonado** [comment]
Hello @ethib137,

I added some changes to what you mentioned. I found that having the label and the described-by in the wrapper, Jaws was able to pick up the description and should change for translations.

Please let me know if I should send a new PR for this and if I should go back to what was previously mentioned.

Thank you for all your help!

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Hey @fortunatomaldonado, we should really keep the described-by and the label on the actual editable element, since that is what's being described. We don't want to change our code, due to a bug in another piece of software. You can test out the   approach I recommended using this screen reader: https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en-US

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @ethib137,

I was able to make the changes.
Please let me know if there is anything that needs to be changed.

Thank you for all your help!

**Comment by fortunatomaldonado** [comment]
Hello @ethib137,

Is there anything else needed to be changed in this PR?
I also saw that Verónica González is assigned in the LPS, should I get in contact with her?

Thank you.

**Pull request closed without merging**
