### PR TITLE
LPS-152121 - Fix border-width token to be added in .table and .table-bordered classes

### PR DESCRIPTION
**Pull request by ilzamcmed**

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Looks Great! Thanks.

**Comment by ethib137** [comment]
ci:forward

**Comment by ethib137** [comment]
Rebased [here](https://github.com/ethib137/liferay-portal/pull/45).

**Pull request closed without merging**
