### PR TITLE
LPS-153050 Border bug in Dialect active tabs

### PR DESCRIPTION
**Pull request by eduardobbgf**

### CODE REVIEW

**Comment by eduardobbgf** [comment]
ci:test:sf

**Comment by eduardobbgf** [comment]
ci:test:relevant

**Comment by eduardobbgf** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Thanks @eduardobbgf a few changes made here: https://github.com/ethib137/liferay-portal/pull/48

**Pull request closed without merging**
