### PR TITLE
LPS-165669 | [HR_60] Adding aria-label to checkbox

### PR DESCRIPTION
**Pull request by igor-franca**
[Related Issue](https://issues.liferay.com/browse/LPS-165669)
Related HRs : HR_60

Description:
Screen reader isn't announcing the elements correctly on Web Content.

 Reproduction Steps:
1. Turn on JAWS and navigate to Content and Data > Web Content
2. Navigate to the Filter and order button and listen to the SR announcement

Expected Results
Checkbox should have label associated with it.

Actual Results
SR announcement for the checkbox next to the Filter and Order is as " Checkbox". There is no label associated with it.

### CODE REVIEW

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/9930

**Comment by victorg1991** [comment]
ci:close

**Comment by victorg1991** [comment]
Wrong pr

**Comment by sandrodw3** [comment]
Reviewed and resent here: https://github.com/liferay-echo/liferay-portal/pull/9935

**Pull request closed without merging**
