### PR TITLE
HR_247/LPS-165264 - add aria-required to form fields

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @ethib137!

https://issues.liferay.com/browse/LPS-165264

This one is pretty straightforward. We have two required form fields in this modal that the screen reader does not identify as 'required'. Adding aria-required fixes this.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1307401_4975

**Comment by ethib137** [comment]
Forwarded to Echo for review: https://github.com/liferay-echo/liferay-portal/pull/9908

**Pull request closed without merging**
