### PR TITLE
LPS-165394 | [HR_105] Removing unnecessary heading

### PR DESCRIPTION
**Pull request by igor-franca**
Related Issue: https://issues.liferay.com/browse/LPS-165394

Related HR:

HR_105 (partially fixes, the additional fix has [already been submitted.](https://github.com/ethib137/liferay-portal/pull/67) )

The solution: Replaces the h4 tag to keep the page organized hierarchically i.e. h1, h2, h3 etc. To not modify the content of the `<h4>` tag to an `<h2>`. Since the title label must be meaningful and convey meaning of relevant content, I modified the `<h4>` tag to a <span> tag.

Reproduction Steps:

Turn on JAWS and navigate to Documents & Media.
Click on the + button to add a Multiple Files Upload.
Press H using JAWS to navigate between the headings.

Actual Results
Screen reader announce two `<h1>` sr-only tags "admin-header" and "navigation", and one `<h4>` "Drop Files Here to Upload".

Warning: Since we are changing tags that are reflected in the whole portal, this is potentially a breaking change.

[Slack question associate](https://liferay.slack.com/archives/C0457LJPCPN/p1665501824832779)

### CODE REVIEW

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1297401_5019

**Comment by catarineaguiar** [comment]
@M-IgorFranca @ethib137 failures not related. Pull looks good to go.

**Comment by M-IgorFranca** [comment]
> @M-IgorFranca @ethib137 failures not related. Pull looks good to go.

Thanks for verify this.

**Comment by M-IgorFranca** [comment]
I need to wait for this [PR](https://github.com/ethib137/liferay-portal/pull/67) to go forward before send the HR_105.

**Comment by barrosdennys** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
@M-IgorFranca this looks good. Can you go ahead and send this PR to @liferay-lima for a final review. Thanks.

Also for all future PRs, make sure to include screenshots of the fix before and after. It will make it much easier to review. 😄

**Review by ethib137 — APPROVED** [review]

**Comment by M-IgorFranca** [comment]
resent [here](https://github.com/liferay-lima/liferay-portal/pull/3606)

**Comment by M-IgorFranca** [comment]
> @M-IgorFranca this looks good. Can you go ahead and send this PR to @liferay-lima for a final review. Thanks.
> 
> Also for all future PRs, make sure to include screenshots of the fix before and after. It will make it much easier to review. smile

resent https://github.com/liferay-lima/liferay-portal/pull/3606

**Pull request closed without merging**
