### PR TITLE
LPS-148835 Dialect Tab Style Guide and Theme

### PR DESCRIPTION
**Pull request by eduardobbgf**

### CODE REVIEW

**Comment by eduardobbgf** [comment]
ci:test:sf

**Comment by eduardobbgf** [comment]
ci:test:relevant

**Comment by eduardobbgf** [comment]
ci:test:sf

**Comment by eduardobbgf** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Nice work @eduardobbgf. I've added some changes [here](https://github.com/ethib137/liferay-portal/pull/25). Please review them and let me know if anything doesn't make sense. Thanks. :)

**Pull request closed without merging**
